export const MENU_CATEGORIES = [
  { id: "entradas", label: "Entradas" },
  { id: "tradicion_mx", label: "Tradición MX" },
  { id: "platos_fuertes", label: "Platos Fuertes" },
  { id: "tacos_y_combos", label: "Tacos y Combos" },
  { id: "burritos", label: "Burritos" },
  { id: "bebidas", label: "Bebidas y Coctelería" },
];

export const MENU_ITEMS = [
  // ─── ENTRADAS ───
  {
    id: "aguachile_chicharron",
    name: "Aguachile de Chicharrón Crujiente",
    description: "Chicharrón crocante bañado en salsa de aguachile, con pepino fresco, cebolla morada y cilantro. Ácido, fresco y lleno de sabor.",
    price: 25000,
    category: "entradas",
  },
  {
    id: "aguachile_camarones",
    name: "Aguachile de Camarones Frescos",
    description: "Camarones frescos marinados en salsa cítrica con notas picantes suaves, acompañados de pepino, cebolla y cilantro.",
    price: 28000,
    category: "entradas",
  },
  {
    id: "aguachile_tripa",
    name: "Aguachile de Tripa Dorada",
    description: "Tripa crocante en contraste con un aguachile intenso y fresco, con vegetales y un toque cítrico balanceado.",
    price: 25000,
    category: "entradas",
  },
  {
    id: "chilaquiles",
    name: "Chilaquiles Tradición de Casa",
    description: "Totopos crujientes bañados en salsa roja, con pollo desmechado o birria, crema y queso. Reconfortantes y llenos de sabor.",
    price: 20000,
    category: "entradas",
  },
  {
    id: "esquites",
    name: "Esquites Callejeros",
    description: "Maíz salteado con mantequilla, crema de leche, queso crema y queso, con un toque de limón y Tajín. Un clásico callejero irresistible.",
    price: 18000,
    category: "entradas",
  },
  {
    id: "papas_birria",
    name: "Papas con Birria Fundida",
    description: "Papas crocantes cubiertas con jugosa birria, queso fundido, salsa ranch, salsa de la casa y su consomé. Intensidad y sabor en cada bocado.",
    price: 23000,
    category: "entradas",
  },
  {
    id: "mini_sopes",
    name: "Trío de Mini Sopes Mexicanos",
    description: "Bases de maíz con guacamole, proteína (birria, chicharrón, tripa), pico de gallo y queso. Pequeños, pero cargados de tradición.",
    price: 20000,
    category: "entradas",
  },
  {
    id: "flautas",
    name: "Flautas Doradas",
    description: "Tortillas rellenas de pollo, fritas hasta dorar y acompañadas con crema, queso y salsa.",
    price: 22000,
    category: "entradas",
  },

  // ─── TRADICIÓN MX ───
  {
    id: "enchiladas_suizas",
    name: "Enchiladas Suizas",
    description: "Tortillas rellenas de pollo o birria, bañadas en salsa roja cremosa, gratinadas con queso. Acompañadas de arroz, frijoles y guacamole.",
    price: 35000,
    category: "tradicion_mx",
  },
  {
    id: "fajitas_pollo",
    name: "Fajitas de Pollo",
    description: "Tiras de pollo salteadas con vegetales, servidas con tortillas y acompañamientos para armar a tu gusto.",
    price: 28000,
    category: "tradicion_mx",
  },
  {
    id: "birriamen",
    name: "Birriamen Especial de la Casa",
    description: "Fusión única: consomé de birria con fideos, carne suave, huevo cocido, aguacate, trozos de cebolla encurtida, queso y mucho sabor.",
    price: 25000,
    category: "tradicion_mx",
  },
  {
    id: "nachos_camaron",
    name: "Nachos Cargados de Camarón",
    description: "Totopos crujientes con camarones salteados, queso fundido, salsa sour cream, salsa de la casa, frijoles y pico de gallo.",
    price: 32000,
    category: "tradicion_mx",
  },
  {
    id: "nachos_chicharron",
    name: "Nachos de Chicharrón",
    description: "Nachos cargados con chicharrón crocante, queso, salsa sour cream, salsa de la casa, frijoles y salsas frescas.",
    price: 30000,
    category: "tradicion_mx",
  },
  {
    id: "quesadillas_pollo",
    name: "Quesadillas de Pollo",
    description: "Tortillas rellenas de pollo y queso fundido, doradas a la plancha.",
    price: 25000,
    category: "tradicion_mx",
  },
  {
    id: "quesadillas_camaron",
    name: "Quesadillas de Camarón",
    description: "Camarones salteados con queso fundido en tortilla caliente y dorada.",
    price: 28000,
    category: "tradicion_mx",
  },
  {
    id: "quesadillas_chorizo",
    name: "Quesadillas de Chorizo",
    description: "Chorizo salteado con queso fundido en tortilla, llenas de sabor y carácter.",
    price: 25000,
    category: "tradicion_mx",
  },
  {
    id: "burger_pollo",
    name: "Burger de Pollo",
    description: "Pechuga de pollo artesanal jugosa adobada y preparada al estilo mexicano, con queso cheddar, vegetales frescos y salsas en pan suave brioche. Con papa a la francesa.",
    price: 30000,
    category: "tradicion_mx",
  },
  {
    id: "burger_birria",
    name: "Burger de Birria",
    description: "Carne de res con birria jugosa en pan brioche, con queso fundido cheddar, vegetales, papa a la francesa y su toque de consomé.",
    price: 32000,
    category: "tradicion_mx",
  },

  // ─── PLATOS FUERTES ───
  {
    id: "ribeye",
    name: "Ribeye",
    description: "Corte jugoso a la parrilla con chimichurri mexicano, acompañado de papas rústicas y ensalada fresca con guacamole.",
    price: 60000,
    category: "platos_fuertes",
  },
  {
    id: "arrachera",
    name: "Arrachera Norteña",
    description: "Entraña marinada y asada, servida con fajitas de vegetales, frijoles refritos y tortillas.",
    price: 45000,
    category: "platos_fuertes",
  },
  {
    id: "pollo_mole",
    name: "Pollo al Mole",
    description: "Suprema de pollo jugosa con mole poblano, acompañada de arroz mexicano.",
    price: 40000,
    category: "platos_fuertes",
  },
  {
    id: "salmon_costra",
    name: "Salmón en Costra",
    description: "Salmón sellado con costra, acompañado de pico de gallo de mango, sobre mole poblano y papas cambray.",
    price: 55000,
    category: "platos_fuertes",
  },
  {
    id: "costillas_cerdo",
    name: "Costillas de Cerdo",
    description: "Costillas de cerdo marinadas y cocidas lentamente hasta quedar suaves y jugosas, terminadas con salsa BBQ de tamarindo y acompañadas de papas rústicas doradas, ahumadas, ligeramente dulces y llenas de sabor.",
    price: 45000,
    category: "platos_fuertes",
  },
  {
    id: "caldoso_charro",
    name: "Caldoso Charro",
    description: "Arroz caldoso al estilo mexicano preparado con tomate y vegetales, chicharrones, chorizo, birria y camarones, crema agria y pétalos de cilantro y cebolla. Un plato completo, colorido y lleno de sabor.",
    price: 36000,
    category: "platos_fuertes",
  },

  // ─── TACOS Y COMBOS ───
  {
    id: "taco_birria",
    name: "Taco de Birria (x3)",
    description: "Taco con carne de res desmechada cocida en chiles y especias, acompañada de una cama de queso fundido y picadillo.",
    price: 35000,
    category: "tacos_y_combos",
  },
  {
    id: "taco_brisket",
    name: "Taco Compadres Brisket (x3)",
    description: "Tortilla dorada con una mezcla volcánica de brisket de res y queso fundido. Coronado con cebolla encurtida.",
    price: 35000,
    category: "tacos_y_combos",
  },
  {
    id: "taco_quesabirria",
    name: "Taco Quesabirria (x3)",
    description: "El mismo taco de birria, pero con el doble de queso. Uno de los favoritos de la casa.",
    price: 35000,
    category: "tacos_y_combos",
  },
  {
    id: "taco_gobernador",
    name: "Taco Gobernador (x3)",
    description: "Taco de camarón, salteado al estilo de la casa, en una cama de queso fundido, con cebolla encurtida y bañado en salsa chipotle.",
    price: 35000,
    category: "tacos_y_combos",
  },
  {
    id: "taco_supreme",
    name: "Taco Supreme (x3)",
    description: "Salmón dorado a la plancha sobre una cama de queso gratinado, acompañado de fresco pico de gallo de mango y servido en tortilla de maíz.",
    price: 35000,
    category: "tacos_y_combos",
  },
  {
    id: "combo_pareja",
    name: "Combo Pareja",
    description: "6 Tacos armados como tú quieras.",
    price: 65000,
    category: "tacos_y_combos",
  },
  {
    id: "combo_compadres",
    name: "Combo Compadres",
    description: "10 Tacos armados como tú quieras.",
    price: 105000,
    category: "tacos_y_combos",
  },

  // ─── BURRITOS ───
  {
    id: "burro_parrillero",
    name: "Burro Parrillero",
    description: "Tortilla de 30cm, con frijol refrito, arroz rojo mexicano, guacamole poblano, chicharrón carnudo, chorizo santarrosano, pollo al estilo pastor, bañados en salsa chipotle y sour cream. Cubierto en costra de queso.",
    price: 36000,
    category: "burritos",
  },
  {
    id: "burro_emperador",
    name: "Burro Emperador",
    description: "Tortilla de 30cm, con frijol refrito, arroz rojo mexicano, guacamole poblano, camarón tigre con salteado de la casa, carne de cerdo al estilo pastor, bañado en salsas chipotle y sour cream. Cubierto en costra de queso.",
    price: 36000,
    category: "burritos",
  },

  // ─── BEBIDAS Y COCTELERÍA ───
  {
    id: "limonada_natural",
    name: "Limonada Natural",
    description: "",
    price: 8000,
    category: "bebidas",
  },
  {
    id: "jugo_agua",
    name: "Jugos Naturales (Agua)",
    description: "Mora, Maracuyá, Lulo, Fresa.",
    price: 8000,
    category: "bebidas",
  },
  {
    id: "jugo_leche",
    name: "Jugos Naturales (Leche)",
    description: "Mora, Maracuyá, Lulo, Fresa.",
    price: 9000,
    category: "bebidas",
  },
  {
    id: "limonadas_frozen",
    name: "Limonadas Frozen",
    description: "Coco, Hierbabuena, Café, Cerezada, Natural.",
    price: 10000,
    category: "bebidas",
  },
  {
    id: "clasicos_mexicanos",
    name: "Clásicos Mexicanos",
    description: "Mangonada, Tamarindo.",
    price: 10000,
    category: "bebidas",
  },
  {
    id: "cafe_americano",
    name: "Café Americano",
    description: "",
    price: 5000,
    category: "bebidas",
  },
  {
    id: "sodas",
    name: "Sodas Refrescantes",
    description: "Frutos rojos y frutos amarillos.",
    price: 10000,
    category: "bebidas",
  },
  {
    id: "gaseosas",
    name: "Gaseosas (CocaCola)",
    description: "",
    price: 5000,
    category: "bebidas",
  },
  {
    id: "cervezas",
    name: "Cervezas",
    description: "Águila, Poker, Corona, Coronita.",
    price: 7000,
    category: "bebidas",
  },
  {
    id: "margarita_jamaica",
    name: "Margarita Jamaica",
    description: "",
    price: 30000,
    category: "bebidas",
  },
  {
    id: "mojito_cubano",
    name: "Mojito Cubano",
    description: "",
    price: 28000,
    category: "bebidas",
  },
  {
    id: "tamarindo_sunset",
    name: "Tamarindo Sunset",
    description: "",
    price: 30000,
    category: "bebidas",
  },
  {
    id: "margarita_blue",
    name: "Margarita Blue",
    description: "",
    price: 30000,
    category: "bebidas",
  },
  {
    id: "pina_colada",
    name: "Piña Colada",
    description: "",
    price: 28000,
    category: "bebidas",
  },
  {
    id: "cantarito",
    name: "Cantarito",
    description: "",
    price: 28000,
    category: "bebidas",
  },
  {
    id: "michelada",
    name: "Michelada Clásica",
    description: "",
    price: 18000,
    category: "bebidas",
  },
  {
    id: "gin_tonic",
    name: "Gin & Tonic",
    description: "",
    price: 28000,
    category: "bebidas",
  },
  {
    id: "margarita_clasica",
    name: "Margarita Clásica",
    description: "",
    price: 28000,
    category: "bebidas",
  },
  {
    id: "manhattan",
    name: "Manhattan",
    description: "",
    price: 32000,
    category: "bebidas",
  },
];
